<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="gunjanpr" failures="2" tests="8" name="TestretryfailedTestcase" time="0.083" errors="0" timestamp="2023-11-28T09:50:31 IST">
  <testcase classname="Listener.RetryLogic" name="Test" time="0.016">
    <skipped/>
  </testcase> <!-- Test -->
  <testcase classname="Listener.RetryLogic" name="Test" time="0.001">
    <skipped/>
  </testcase> <!-- Test -->
  <testcase classname="Listener.RetryLogic" name="Test" time="0.001">
    <skipped/>
  </testcase> <!-- Test -->
  <testcase classname="Listener.RetryLogic" name="Test" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Listener.RetryLogic.Test(RetryLogic.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test -->
  <testcase classname="Listener.RetryLogic" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="Listener.RetryLogic" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="Listener.RetryLogic" name="Test2" time="0.0">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="Listener.RetryLogic" name="Test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Listener.RetryLogic.Test2(RetryLogic.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- TestretryfailedTestcase -->
